### ISSUE TITLE
Plateforms Activity 

### ISSUE THREAD

**Issue by ahmednafea** [Open-Source-Community/GamersHub-AndroidApp#12]
An activity for choosing the Platforms

**Comment by amrtaher1234** [comment]
any progress ?

**Comment by ahmednafea** [comment]
![mouse](https://user-images.githubusercontent.com/32443261/42140710-1e085470-7da3-11e8-9ed1-81dc898d36a2.png)
![nintendo](https://user-images.githubusercontent.com/32443261/42140711-1e53e9d0-7da3-11e8-886b-3dcdc1ec5298.png)
![platformssearchback](https://user-images.githubusercontent.com/32443261/42140712-1e9b6bac-7da3-11e8-85dd-715232a7feb6.jpg)
![playstation3](https://user-images.githubusercontent.com/32443261/42140713-1eec87a8-7da3-11e8-8c05-c40a18e3d2f3.png)
![playstation4](https://user-images.githubusercontent.com/32443261/42140714-1f3e3666-7da3-11e8-8fb4-d1ddd6541f06.png)
![wii](https://user-images.githubusercontent.com/32443261/42140715-20021b6c-7da3-11e8-8ef1-28f1851f0844.png)
![xbox360](https://user-images.githubusercontent.com/32443261/42140716-207a93bc-7da3-11e8-9226-ab877eff960a.png)
![xboxone](https://user-images.githubusercontent.com/32443261/42140717-214589fa-7da3-11e8-853c-42f2f674af00.png)
//---------------------------------------------
this is the drawable Files which i used

**Comment by ahmednafea** [comment]
![image](https://user-images.githubusercontent.com/32443261/42140800-0b043dc0-7da4-11e8-96db-13f75b63b9ff.png)
//----------------------------------------------------------------------
that's the Final result

**Comment by amrtaher1234** [comment]
Nice

**Comment by amrtaher1234** [comment]
Maynf3sh teshel el logo beta3 ps4 w te7ot haga tanya?

**Comment by ahmednafea** [comment]
هو داينمك وهنظبط الدنيا كباك ايند لمى نظبط الفاير بيز لا تقلق بس انا عاوز ارفع الفايلات بقى افتح الماسينجر
